services:
  core-keeper:
    image: ghcr.io/hangeol-chang/ck-server-arm:latest
    network_mode: "host"
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: ck-server
    restart: always
    volumes:
      - ./data:/home/steam/core-keeper-data
    env_file:
      - path: core.env